version: '3'

services:
  api:
    build: "./backend"
    container_name: api
    ports:
      - "5000:5000"
    volumes:
      - "./backend/:/app"

  web:
    build: "./frontend"
    container_name: web
    ports:
      - "3000:3000"
    volumes:
      - "./frontend/:/src"

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - tms-data:/data/db
    
volumes:
  tms-data: {}